# Generated by Selenium IDE
#Importações de pacotes:
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

#Classes e definições:
class TestConsultarMantis():
    def setup_method(self, method):
        self.driver = webdriver.Chrome('C:/Users/aclecio11/PycharmProjects/fts_132/drivers/chrome/97/chromedriver.exe')
        self.driver.implicitly_wait(30) # Orobô irá esperar por ate 30 segundos pelos elementos
        self.driver.maximize_window() #Esse comando vai maximizar a janela do navegador
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_1_iterasys(self):
        self.driver.get("https://iterasys.com.br/")
        self.driver.set_window_size(1346, 708)
        self.driver.find_element(By.ID, "searchtext").send_keys("Mantis")
        self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()                    #time.sleep(3) #pausa forçada "alfinete" - sempre remover antes de salvar no repositório
        self.driver.find_element(By.CSS_SELECTOR, ".comprar").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".item-title").text == "Mantis"
        assert self.driver.find_element(By.CSS_SELECTOR, ".new-price").text == "R$ 59,99"

